# Data Exploration

In [11]:
import pandas as pd

df = pd.read_csv('train-data.csv')
df.head()

   Unnamed: 0                              Name  ...  New_Price  Price
0           0            Maruti Wagon R LXI CNG  ...        NaN   1.75
1           1  Hyundai Creta 1.6 CRDi SX Option  ...        NaN  12.50
2           2                      Honda Jazz V  ...  8.61 Lakh   4.50
3           3                 Maruti Ertiga VDI  ...        NaN   6.00
4           4   Audi A4 New 2.0 TDI Multitronic  ...        NaN  17.74

[5 rows x 14 columns]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         6019 non-null   int64
 1   Name               6019 non-null   object
 2   Location           6019 non-null   object
 3   Year               6019 non-null   int64
 4   Kilometers_Driven  6019 non-null   int64
 5   Fuel_Type          6019 non-null   object
 6   Transmission       6019 non-null   object
 7   Owner_Type         6019 non-null   object
 8   Mileage            6017 non-null   object
 9   Engine             5983 non-null   object
 10  Power              5983 non-null   object
 11  Seats              5977 non-null   float64
 12  New_Price          824 non-null    object
 13  Price              6019 non-null   float64
dtypes: float64(2), int64(3), object(9)
memory usage: 658.5+ KB

In [13]:
pd.options.display.float_format = '{:,.1f}'.format
df.describe()

       Unnamed: 0    Year  Kilometers_Driven   Seats   Price
count     6,019.0 6,019.0            6,019.0 5,977.0 6,019.0
mean      3,009.0 2,013.4           58,738.4     5.3     9.5
std       1,737.7     3.3           91,268.8     0.8    11.2
min           0.0 1,998.0              171.0     0.0     0.4
25%       1,504.5 2,011.0           34,000.0     5.0     3.5
50%       3,009.0 2,014.0           53,000.0     5.0     5.6
75%       4,513.5 2,016.0           73,000.0     5.0     9.9
max       6,018.0 2,019.0        6,500,000.0    10.0   160.0

In [14]:
df.describe(include='O')

                          Name Location Fuel_Type  ...   Engine   Power   New_Price
count                     6019     6019      6019  ...     5983    5983         824
unique                    1876       11         5  ...      146     372         540
top     Mahindra XUV500 W8 2WD   Mumbai    Diesel  ...  1197 CC  74 bhp  95.13 Lakh
freq                        49      790      3205  ...      606     235           6

[4 rows x 9 columns]

In [15]:
# from ydata_profiling import ProfileReport
# profile = ProfileReport(df, title="Pandas Profiling Report")
# profile.to_file("your_report.html")

> Data Preprocessing Steps:
* Unnamed: 0 > Drop
* Name > Feature Engineering > Brand, Model
* Location > encoding
* Year > Age =  Current Year - Year (Max Year in dataset + 1 - Year)
* Kilometers_Driven > Handle outliers
* Fuel_Type, Transmission & Owner_Type > encoding
* Fuel_Type > Take care of 'Electric' category
* Mileage, Engine & Power > Extract numeric values & convert to float (Take care of Units)
* Seats > Handle Zeros
* New Price > Drop (Too many missing values)

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
pd.options.display.float_format = '{:,.3f}'.format
df.isnull().mean() *100

Unnamed: 0           0.000
Name                 0.000
Location             0.000
Year                 0.000
Kilometers_Driven    0.000
Fuel_Type            0.000
Transmission         0.000
Owner_Type           0.000
Mileage              0.033
Engine               0.598
Power                0.598
Seats                0.698
New_Price           86.310
Price                0.000
dtype: float64

In [18]:
# Drop Unnamed: 0 & New Price
df.drop(columns=['Unnamed: 0', 'New_Price'], inplace=True)

# Name

In [19]:
df.Name.sample(10)

3607    Mercedes-Benz New C-Class C250 Avantgarde
2294                          Honda City 1.5 V AT
2987                    Hyundai Verna 1.6 SX VTVT
2459            Ford EcoSport 1.5 Diesel Titanium
5353                       Volkswagen Polo GT TSI
1974                           BMW 7 Series 740Li
3160                          Maruti Alto 800 LXI
2517                       Hyundai Verna 1.4 VTVT
5384                   Tata Zest Revotron 1.2T XM
4064                    Ford Figo Diesel Titanium
Name: Name, dtype: object

In [20]:
df.Name.str.contains('Land Rover').sum()

np.int64(60)

In [21]:
df.Name[df.Name.str.contains('Land Rover')].sample(5)

2263    Land Rover Range Rover 2.2L Prestige
404     Land Rover Range Rover 2.2L Prestige
521       Land Rover Range Rover HSE Dynamic
5382    Land Rover Range Rover 2.2L Prestige
3410         Land Rover Freelander 2 HSE SD4
Name: Name, dtype: object

In [22]:
sample_car = df.loc[10, 'Name']
sample_car.split(' ')[0]  # Brand

'Maruti'

In [23]:
def get_brand(name):
    if name.startswith('Land Rover'):
        return 'Land Rover'
    return name.split(' ')[0]

sample_car = df.loc[1505, 'Name']
get_brand(sample_car)

'Land Rover'

In [24]:
df['Brand'] = df.Name.apply(get_brand)

In [25]:
df.head()

                               Name    Location  Year  ...  Seats  Price    Brand
0            Maruti Wagon R LXI CNG      Mumbai  2010  ...  5.000  1.750   Maruti
1  Hyundai Creta 1.6 CRDi SX Option        Pune  2015  ...  5.000 12.500  Hyundai
2                      Honda Jazz V     Chennai  2011  ...  5.000  4.500    Honda
3                 Maruti Ertiga VDI     Chennai  2012  ...  7.000  6.000   Maruti
4   Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013  ...  5.000 17.740     Audi

[5 rows x 13 columns]

In [26]:
df[df.Name.str.contains('Land Rover')].sample(5)

                                              Name  ...       Brand
5382          Land Rover Range Rover 2.2L Prestige  ...  Land Rover
2528               Land Rover Discovery SE 3.0 TD6  ...  Land Rover
5067  Land Rover Discovery Sport SD4 HSE Luxury 7S  ...  Land Rover
4247                    Land Rover Freelander 2 SE  ...  Land Rover
5311                Land Rover Freelander 2 TD4 SE  ...  Land Rover

[5 rows x 13 columns]

In [27]:
import numpy as np
for i in np.random.randint(0, len(df), 5):
    sample_car = df.loc[i, 'Name']
    print(sample_car.split(' ')[1])   # MODEL

Creta
Swift
New
Superb
Etios

In [28]:
sample_car = df[df.Name.str.contains('Land Rover')].reset_index().loc[50, 'Name']
print(sample_car)

Land Rover Discovery Sport TD4 HSE 7S

In [29]:
def get_model(name):
    if name.startswith('Land Rover Range Rover'):
        return 'Range Rover'
    elif name.startswith('Land Rover'):
        return name.split(' ')[2]
    else:
        return name.split(' ')[1]
    
df['Model'] = df.Name.apply(get_model)

In [30]:
df[df.Name.str.contains('Land Rover')].sample(5)

                                              Name  ...        Model
3839  Land Rover Discovery 3 TDV6 Diesel Automatic  ...    Discovery
5539     Land Rover Discovery Sport SD4 HSE Luxury  ...    Discovery
2139    Land Rover Range Rover Evoque 2.0 TD4 Pure  ...  Range Rover
1513              Land Rover Range Rover 2.2L Pure  ...  Range Rover
1299                Land Rover Discovery 4 TDV6 SE  ...    Discovery

[5 rows x 14 columns]

In [31]:
df.describe(include='O')

                          Name Location Fuel_Type  ...   Power   Brand  Model
count                     6019     6019      6019  ...    5983    6019   6019
unique                    1876       11         5  ...     372      31    214
top     Mahindra XUV500 W8 2WD   Mumbai    Diesel  ...  74 bhp  Maruti  Swift
freq                        49      790      3205  ...     235    1211    353

[4 rows x 10 columns]

In [32]:
df.drop(columns=['Name'], inplace=True)

# Age

In [33]:
df['Age'] = df.Year.max() + 1 - df.Year

# Kilometers_Driven

In [34]:
import seaborn as sns
import plotly.express as px

px.histogram(df, x='Kilometers_Driven', marginal='box', title='Km Distribution')

In [35]:
df[df.Kilometers_Driven == df.Kilometers_Driven.max()]

     Location  Year  Kilometers_Driven Fuel_Type  ...  Price Brand Model Age
2328  Chennai  2017            6500000    Diesel  ... 65.000   BMW    X5   3

[1 rows x 14 columns]

In [36]:
km_outlier = df[df.Kilometers_Driven == df.Kilometers_Driven.max()].index
df.drop(index=km_outlier, inplace=True)

In [37]:
px.histogram(df, x='Kilometers_Driven', marginal='box', title='Km Distribution')

In [38]:
df.Kilometers_Driven.quantile([0.8, 0.9, 0.95, 0.99, 0.995, 0.999, 1])

0.800    79,000.000
0.900    96,893.600
0.950   120,000.000
0.990   171,871.500
0.995   200,000.000
0.999   299,988.474
1.000   775,000.000
Name: Kilometers_Driven, dtype: float64

In [39]:
df[df.Kilometers_Driven > df.Kilometers_Driven.quantile(0.999)].shape

(7, 14)

In [40]:
df[df.Kilometers_Driven > df.Kilometers_Driven.quantile(0.999)]

       Location  Year  Kilometers_Driven  ...       Brand    Model Age
340     Kolkata  2013             775000  ...       Skoda  Octavia   7
358     Chennai  2009             620000  ...     Hyundai      i10  11
1860    Chennai  2013             720000  ...  Volkswagen    Vento   7
2823    Chennai  2015             480000  ...  Volkswagen    Jetta   5
3092    Kolkata  2015             480000  ...       Honda     City   5
3649     Jaipur  2008             300000  ...        Tata   Indigo  12
4491  Bangalore  2013             445000  ...     Hyundai      i20   7

[7 rows x 14 columns]

In [41]:
q1 = df.Kilometers_Driven.quantile(0.25)
q3 = df.Kilometers_Driven.quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

print(f"Lower Bound: {lower_bound}, Upper Bound: {upper_bound}")

Lower Bound: -24500.0, Upper Bound: 131500.0

In [42]:
df[df.Kilometers_Driven > upper_bound].shape

(201, 14)

In [43]:
df_c = df.copy()
df_c = df_c[df_c.Kilometers_Driven < df.Kilometers_Driven.quantile(0.999)]

In [44]:
px.histogram(df_c, x='Kilometers_Driven', marginal='box', title='Km Distribution')

In [45]:
df.head()

     Location  Year  Kilometers_Driven Fuel_Type  ...  Price    Brand   Model Age
0      Mumbai  2010              72000       CNG  ...  1.750   Maruti   Wagon  10
1        Pune  2015              41000    Diesel  ... 12.500  Hyundai   Creta   5
2     Chennai  2011              46000    Petrol  ...  4.500    Honda    Jazz   9
3     Chennai  2012              87000    Diesel  ...  6.000   Maruti  Ertiga   8
4  Coimbatore  2013              40670    Diesel  ... 17.740     Audi      A4   7

[5 rows x 14 columns]

# Fuel_Type

In [46]:
df_c.Fuel_Type.unique()

array(['CNG', 'Diesel', 'Petrol', 'LPG', 'Electric'], dtype=object)

In [47]:
df_c[df_c.Fuel_Type == 'Electric']

     Location  Year  Kilometers_Driven Fuel_Type  ...  Price     Brand  Model Age
4446  Chennai  2016              50000  Electric  ... 13.000  Mahindra      E   4
4904   Mumbai  2011              44000  Electric  ... 12.750    Toyota  Prius   9

[2 rows x 14 columns]

In [48]:
df_c.isna().mean() * 100

Location            0.000
Year                0.000
Kilometers_Driven   0.000
Fuel_Type           0.000
Transmission        0.000
Owner_Type          0.000
Mileage             0.033
Engine              0.599
Power               0.599
Seats               0.699
Price               0.000
Brand               0.000
Model               0.000
Age                 0.000
dtype: float64

In [49]:
df_c.dropna(inplace=True)

In [50]:
df_c.isna().mean() * 100

Location            0.000
Year                0.000
Kilometers_Driven   0.000
Fuel_Type           0.000
Transmission        0.000
Owner_Type          0.000
Mileage             0.000
Engine              0.000
Power               0.000
Seats               0.000
Price               0.000
Brand               0.000
Model               0.000
Age                 0.000
dtype: float64

In [51]:
df_c.Fuel_Type.unique()

array(['CNG', 'Diesel', 'Petrol', 'LPG'], dtype=object)

# Mileage

In [52]:
df_c.Mileage.str.split(' ').str[1].unique()

array(['km/kg', 'kmpl'], dtype=object)

In [53]:
df_c.Fuel_Type.unique()

array(['CNG', 'Diesel', 'Petrol', 'LPG'], dtype=object)

In [54]:
# fuel densities (kg/L)
fuel_densities = {
    "CNG": 0.43,
    "Diesel": 0.832,
    "Petrol": 0.74,
    "LPG": 0.54
}

def convert_to_kmpl(row):
    fuel = row['Fuel_Type']
    mileage = float(row['Mileage'].split()[0])
    unit = row['Mileage'].split()[1] 
    
    if fuel in fuel_densities:
        if unit == 'km/kg':
            return mileage * fuel_densities[fuel]
        else:
            return mileage
    return np.nan

# Apply conversion to DataFrame
df_c['Mileage'] = df_c.apply(convert_to_kmpl, axis=1)

In [55]:
df_c.isna().mean() * 100

Location            0.000
Year                0.000
Kilometers_Driven   0.000
Fuel_Type           0.000
Transmission        0.000
Owner_Type          0.000
Mileage             0.000
Engine              0.000
Power               0.000
Seats               0.000
Price               0.000
Brand               0.000
Model               0.000
Age                 0.000
dtype: float64

# Engine

In [56]:
df_c.Engine.str.split(' ').str[1].unique()

array(['CC'], dtype=object)

In [57]:
def get_engine(engine):
    return float(engine.split(' ')[0]) 

df_c['Engine'] = df_c['Engine'].apply(get_engine)

# Power

In [58]:
df_c.Power.str.split(' ').str[1].unique()

array(['bhp'], dtype=object)

In [59]:
df_c.Power.sample(10)

1326    89.84 bhp
176       112 bhp
4393     67.1 bhp
1987       74 bhp
3885      118 bhp
3782       63 bhp
2710    187.7 bhp
1317       75 bhp
2851       67 bhp
2729    158.8 bhp
Name: Power, dtype: object

In [60]:
def get_power(power):
    try:
        return float(power.split(' ')[0])
    except:
        return np.nan

df_c['Power'] = df_c['Power'].apply(get_power)
# df_c['Power'] = pd.to_numeric(df_c['Power'].str.split(' ').str[0], errors='coerce')

In [61]:
df_c.isna().mean() * 100

Location            0.000
Year                0.000
Kilometers_Driven   0.000
Fuel_Type           0.000
Transmission        0.000
Owner_Type          0.000
Mileage             0.000
Engine              0.000
Power               1.726
Seats               0.000
Price               0.000
Brand               0.000
Model               0.000
Age                 0.000
dtype: float64

# Seats

In [62]:
df_c = df_c[df_c.Seats > 0]

In [63]:
df_c.Seats.value_counts(normalize=True) * 100

Seats
5.000    83.875
7.000    11.297
8.000     2.246
4.000     1.659
6.000     0.520
2.000     0.268
10.000    0.084
9.000     0.050
Name: proportion, dtype: float64

normalize=True → بدل ما يرجعلك عدد المرات، بيرجعلك النسبة المئوية (الاحتمال).
يعني بيقسم التكرار على إجمالي عدد الصفوف.

# Univariate Analysis

In [64]:
df_c.head()

     Location  Year  Kilometers_Driven Fuel_Type  ...  Price    Brand   Model  Age
0      Mumbai  2010              72000       CNG  ...  1.750   Maruti   Wagon   10
1        Pune  2015              41000    Diesel  ... 12.500  Hyundai   Creta    5
2     Chennai  2011              46000    Petrol  ...  4.500    Honda    Jazz    9
3     Chennai  2012              87000    Diesel  ...  6.000   Maruti  Ertiga    8
4  Coimbatore  2013              40670    Diesel  ... 17.740     Audi      A4    7

[5 rows x 14 columns]

In [65]:
df.describe()

           Year  Kilometers_Driven     Seats     Price       Age
count 6,018.000          6,018.000 5,976.000 6,018.000 6,018.000
mean  2,013.358         57,668.048     5.279     9.470     6.642
std       3.270         37,878.783     0.809    11.166     3.270
min   1,998.000            171.000     0.000     0.440     1.000
25%   2,011.000         34,000.000     5.000     3.500     4.000
50%   2,014.000         53,000.000     5.000     5.640     6.000
75%   2,016.000         73,000.000     5.000     9.950     9.000
max   2,019.000        775,000.000    10.000   160.000    22.000

In [66]:
df_c = df_c.reset_index(drop=True)

In [67]:
df_c.describe(include='O')

       Location Fuel_Type Transmission Owner_Type   Brand  Model
count      5966      5966         5966       5966    5966   5966
unique       11         4            2          4      31    211
top      Mumbai    Diesel       Manual      First  Maruti  Swift
freq        784      3190         4261       4894    1197    343

In [68]:
import plotly.express as px

numeric_cols = df_c.select_dtypes(include=[np.number]).columns.tolist()

for col in numeric_cols:
    fig = px.histogram(df_c, x=col, marginal='box', title=f'Distribution of {col}', nbins=30)
    fig.show()

In [69]:
df_c = df_c[df_c.Year >= 2006]
df_c['Mileage'] = df_c['Mileage'].replace(0, np.nan)
df_c = df_c[df_c.Engine < 3000]
df_c = df_c[df_c.Kilometers_Driven < 180000]
df_c = df_c[df_c.Power < 270]

In [70]:
for col in numeric_cols:
    fig = px.histogram(df_c, x=col, marginal='box', title=f'Distribution of {col}', nbins=30)
    fig.show()

In [71]:
dropped_rows_pct = 1 - df_c.shape[0] / len(df)
print(f"Dropped rows percentage: {dropped_rows_pct:.2%}")

Dropped rows percentage: 6.63%

In [72]:
df_c.isna().mean() * 100

Location            0.000
Year                0.000
Kilometers_Driven   0.000
Fuel_Type           0.000
Transmission        0.000
Owner_Type          0.000
Mileage             0.463
Engine              0.000
Power               0.000
Seats               0.000
Price               0.000
Brand               0.000
Model               0.000
Age                 0.000
dtype: float64

In [73]:
df_c.describe()

           Year  Kilometers_Driven   Mileage  ...     Seats     Price       Age
count 5,619.000          5,619.000 5,593.000  ... 5,619.000 5,619.000 5,619.000
mean  2,013.690         55,170.487    18.412  ...     5.279     9.182     6.310
std       2.858         30,438.283     4.094  ...     0.769    10.065     2.858
min   2,006.000            171.000     5.676  ...     2.000     0.440     1.000
25%   2,012.000         33,000.000    15.500  ...     5.000     3.600     4.000
50%   2,014.000         52,000.000    18.500  ...     5.000     5.740     6.000
75%   2,016.000         71,436.500    21.100  ...     5.000     9.750     8.000
max   2,019.000        179,000.000    28.400  ...    10.000   160.000    14.000

[8 rows x 8 columns]

# Data Splitting

- Category Columns > Encoding
- Numeric Columns > Handle missing values and Scaling

In [74]:
# Data splitting

x = df_c.drop(columns=['Price', 'Year'])
y = df_c['Price']

In [85]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

هو parameter بيتحط في خوارزميات الـ Machine Learning أو في عمليات الـ Random Split (زي train_test_split)، وظيفته:

👉 يثبت العشوائية عشان النتايج تفضل نفسها كل مرة تشغّل الكود.

📌 الخلاصة

random_state = Seed للعشوائية.

بيخلي التجارب قابلة للتكرار (reproducible).

مهم جدًا في البحث العلمي أو الشغل الجماعي → عشان أي حد يشغّل الكود يلاقي نفس النتائج.

In [76]:
x_train.shape

(4495, 12)

In [87]:
# Splitting columns

num_cols = ['Kilometers_Driven', 'Mileage', 'Engine', 'Power', 'Age'] # Impute Missing Values and Scale
nom_cat_cols = ['Location', 'Fuel_Type', 'Transmission', 'Brand', 'Model'] # USE Binary Encoding
ord_cat_cols = ['Owner_Type']  # Use ORDINAL ENCODING

In [78]:
!pip install category_encoders

Requirement already satisfied: category_encoders in c:\users\mohamed ezzat\appdata\local\programs\python\python310\lib\site-packages (2.8.1)
Requirement already satisfied: numpy>=1.14.0 in c:\users\mohamed ezzat\appdata\local\programs\python\python310\lib\site-packages (from category_encoders) (2.1.3)
Requirement already satisfied: pandas>=1.0.5 in c:\users\mohamed ezzat\appdata\local\programs\python\python310\lib\site-packages (from category_encoders) (2.3.2)
Requirement already satisfied: patsy>=0.5.1 in c:\users\mohamed ezzat\appdata\local\programs\python\python310\lib\site-packages (from category_encoders) (1.0.1)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\mohamed ezzat\appdata\local\programs\python\python310\lib\site-packages (from category_encoders) (1.7.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\mohamed ezzat\appdata\local\programs\python\python310\lib\site-packages (from category_encoders) (1.15.3)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\mohamed ezzat\appdata\local\programs\python\python310\lib\site-packages (from category_encoders) (0.14.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mohamed ezzat\appdata\roaming\python\python310\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mohamed ezzat\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mohamed ezzat\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\mohamed ezzat\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\mohamed ezzat\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\mohamed ezzat\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in c:\users\mohamed ezzat\appdata\roaming\python\python310\site-packages (from statsmodels>=0.9.0->category_encoders) (25.0)

In [90]:
# Splitting columns

num_cols = ['Kilometers_Driven', 'Mileage', 'Engine', 'Power', 'Age'] # Impute Missing Values and Scale
nom_cat_cols = ['Location', 'Fuel_Type', 'Transmission', 'Brand', 'Model'] # USE Binary Encoding
ord_cat_cols = ['Owner_Type']  # Use ORDINAL ENCODING

In [121]:
from category_encoders import BinaryEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

# Preprocessing for numerical data
numerical_transformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='median')), 
                                        ('scaler', StandardScaler())])

# Preprocessing for categorical data
nominal_categorical_transformer = Pipeline(steps=[('binary', BinaryEncoder())])
ordinal_categorical_transformer = Pipeline(steps=[('ordinal', OrdinalEncoder(categories=[['Fourth & Above', 'Third', 'Second', 'First']]))])

# Bundle preprocessing for numerical and categorical data
preprocessor = ColumnTransformer(transformers=[('num_prep', numerical_transformer, num_cols),
                                               ('nom_prep', nominal_categorical_transformer, nom_cat_cols),
                                               ('ord_prep', ordinal_categorical_transformer, ord_cat_cols)])

x_train_prep = preprocessor.fit_transform(x_train)
x_test_prep = preprocessor.transform(x_test)

In [92]:
x_train_prep.shape

(4495, 28)

In [93]:
x_train_prep

array([[-1.08423424, -0.4720888 , -0.72760357, ...,  0.        ,
         1.        ,  3.        ],
       [ 0.4521476 ,  0.02363623,  2.62788967, ...,  1.        ,
         0.        ,  3.        ],
       [-1.14876227,  0.14573599, -0.72572795, ...,  1.        ,
         1.        ,  3.        ],
       ...,
       [ 2.21735226, -1.42935092,  2.61851154, ...,  0.        ,
         1.        ,  2.        ],
       [ 0.74634838,  0.61459907, -1.10272859, ...,  0.        ,
         0.        ,  2.        ],
       [-0.72465551, -0.14730344, -0.72760357, ...,  1.        ,
         1.        ,  3.        ]])

In [94]:
# Model Building
from sklearn.linear_model import LinearRegression

# Linear Regression
lr = LinearRegression()
lr.fit(x_train_prep, y_train)

# Predictions
y_pred = lr.predict(x_test_prep)

# Model Evaluation
print('Training Accuracy:', lr.score(x_train_prep, y_train))
print('Testing Accuracy', lr.score(x_test_prep, y_test))

Training Accuracy: 0.7399991262351754
Testing Accuracy 0.7573599302557426

In [95]:
# Model Building
from sklearn.linear_model import LinearRegression

# Linear Regression
lr = LinearRegression()
lr.fit(x_train_prep, y_train)

# Predictions
y_pred = lr.predict(x_test_prep)

print('Intercept:', lr.intercept_)
print('Coefficients:', lr.coef_)

Intercept: 9.75042476974708
Coefficients: [-8.90155690e-01 -1.24033059e-01  1.18462563e+00  5.28321100e+00
 -2.63386713e+00 -8.18486731e-01  1.00674375e+00  8.65178500e-01
 -4.34365940e-01  1.07694599e+00  4.07585365e-01 -1.14104436e+00
  9.10786482e-01 -9.10786482e-01  6.61867211e+00 -1.30306878e-01
 -1.39771606e+00  4.14068629e-01 -2.71369839e+00  1.58651269e+00
  1.30750935e+00 -1.32931466e+00 -5.35514811e-03 -3.10238440e-03
 -1.05808800e+00 -6.10802860e-01  7.57654516e-01  6.83253308e-01]

In [ ]:
# Predictions
y_pred = lr.predict(x_test_prep)  # bn3mel el weights ely fook multiply el feature (x_test_prep)

print('Intercept:', lr.intercept_)
print('Coefficients:', lr.coef_)

Training Accuracy: 0.7399991262351754
Testing Accuracy 0.7573599302557426

In [ ]:
preprocessor.named_transformers_['num_prep'].named_steps['imputer'].statistics_  # Median values of the numerical features

array([5.200e+04, 1.850e+01, 1.493e+03, 9.370e+01, 6.000e+00])

In [98]:
for col in num_cols:
    print(f'Median of {col}: {x_train[col].median()}')

Median of Kilometers_Driven: 52000.0
Median of Mileage: 18.5
Median of Engine: 1493.0
Median of Power: 93.7
Median of Age: 6.0

In [99]:
x_train_prep = preprocessor.fit_transform(x_train)
x_test_prep = preprocessor.transform(x_test)

x_train_prep = preprocessor.fit_transform(x_train)  
بتتعلم الميديان مثلا ثم تملى بيه اللي هو ترانسفورم

In [100]:
# Model Building
from sklearn.linear_model import LinearRegression

# Linear Regression
lr = LinearRegression() # lr is an instance from class (linearRegression)
lr.fit(x_train_prep, y_train)  # Learn weights from training data OLS (Normal Equation)

# Predictions
y_pred = lr.predict(x_test_prep)

print('Intercept:', lr.intercept_)  # w0
print('Coefficients:', lr.coef_)  # w1, w2, w3

Intercept: 9.75042476974708
Coefficients: [-8.90155690e-01 -1.24033059e-01  1.18462563e+00  5.28321100e+00
 -2.63386713e+00 -8.18486731e-01  1.00674375e+00  8.65178500e-01
 -4.34365940e-01  1.07694599e+00  4.07585365e-01 -1.14104436e+00
  9.10786482e-01 -9.10786482e-01  6.61867211e+00 -1.30306878e-01
 -1.39771606e+00  4.14068629e-01 -2.71369839e+00  1.58651269e+00
  1.30750935e+00 -1.32931466e+00 -5.35514811e-03 -3.10238440e-03
 -1.05808800e+00 -6.10802860e-01  7.57654516e-01  6.83253308e-01]

In [101]:
preprocessor.get_feature_names_out()

array(['num_prep__Kilometers_Driven', 'num_prep__Mileage',
       'num_prep__Engine', 'num_prep__Power', 'num_prep__Age',
       'nom_prep__Location_0', 'nom_prep__Location_1',
       'nom_prep__Location_2', 'nom_prep__Location_3',
       'nom_prep__Fuel_Type_0', 'nom_prep__Fuel_Type_1',
       'nom_prep__Fuel_Type_2', 'nom_prep__Transmission_0',
       'nom_prep__Transmission_1', 'nom_prep__Brand_0',
       'nom_prep__Brand_1', 'nom_prep__Brand_2', 'nom_prep__Brand_3',
       'nom_prep__Brand_4', 'nom_prep__Model_0', 'nom_prep__Model_1',
       'nom_prep__Model_2', 'nom_prep__Model_3', 'nom_prep__Model_4',
       'nom_prep__Model_5', 'nom_prep__Model_6', 'nom_prep__Model_7',
       'ord_prep__Owner_Type'], dtype=object)

In [109]:
feature_importance = dict(zip(preprocessor.get_feature_names_out(), lr.coef_))
feature_importance = pd.Series(feature_importance).sort_values()
px.bar(feature_importance, width=800, orientation='h',height=900, title='Feature Importance')

1️⃣ ليه coef_ فيها Underscore (_)؟

في مكتبة scikit-learn:

أي attributes (قيم بيحسبها الموديل بعد التدريب) بيكون اسمها منتهي بـ _.

ده Convention في sklearn → علشان يفرقوا بين parameters (اللي إنت بتمررها عند الإنشاء) و attributes/learned values (اللي الموديل بيتعلمها بعد .fit()).

In [110]:
# Model Evaluation
print('Training Accuracy:', lr.score(x_train_prep, y_train))
print('Tetsing Accuracy:', lr.score(x_test_prep, y_test))

Training Accuracy: 0.7399991262351754
Tetsing Accuracy: 0.7573599302557426

In [115]:
# Plynomial Regresssion 
from sklearn.preprocessing import PolynomialFeatures


# Preprocessing for numerical data
numerical_transformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                                        ('poly', PolynomialFeatures(degree=2)), 
                                        ('scaler', StandardScaler())])

# Preprocessing for categorical data
nominal_categorical_transformer = Pipeline(steps=[('binary', BinaryEncoder())])
ordinal_categorical_transformer = Pipeline(steps=[('ordinal', OrdinalEncoder(categories=[['Fourth & Above', 'Third', 'Second', 'First']]))])

# Bundle preprocessing for numerical and categorical data
preprocessor = ColumnTransformer(transformers=[('num_prep', numerical_transformer, num_cols),
                                               ('nom_prep', nominal_categorical_transformer, nom_cat_cols),
                                               ('ord_prep', ordinal_categorical_transformer, ord_cat_cols)])

x_train_poly = preprocessor.fit_transform(x_train)
x_test_poly = preprocessor.transform(x_test)

In [119]:
x_test_poly.shape

(1124, 44)

In [120]:
lr_poly = LinearRegression()

lr_poly.fit(x_train_poly, y_train)

# Accuracy
print('Trainig Accuracy', lr_poly.score(x_train_poly, y_train))
print('Testing Accuracy', lr_poly.score(x_test_poly, y_test))

Trainig Accuracy 0.8623732927987561
Testing Accuracy 0.8697319236991381

In [125]:
# Ridge Regression
from  sklearn.linear_model import Ridge 
from sklearn.metrics import mean_squared_error, r2_score

ridge = Ridge()
ridge.fit(x_train_prep, y_train)

# Predictions
y_pred = ridge.predict(x_test_prep)

# Model Evaluation
print('RMSE:', mean_squared_error(y_test, y_pred))
print('R2:', r2_score(y_test, y_pred))

RMSE: 21.836374571441247
R2: 0.7573864996073563

In [ ]:
# Ridge Regression
from  sklearn.linear_model import Ridge 
from sklearn.metrics import mean_squared_error, r2_score

ridge = Ridge() # alpha = 1 by default
ridge.fit(x_train_prep, y_train)

# Predictions
y_pred = ridge.predict(x_test_prep)

# Model Evaluation
print('RMSE:', mean_squared_error(y_test, y_pred))
print('R2:', r2_score(y_test, y_pred))

In [130]:
# Ridge Regression
from  sklearn.linear_model import Ridge 
from sklearn.metrics import mean_squared_error, r2_score

ridge = Ridge()
ridge.fit(x_train_prep, y_train)

# Predictions
y_pred = ridge.predict(x_test_prep)

# Model Evaluation
print('RMSE:', mean_squared_error(y_test, y_pred))
print('R2:', r2_score(y_test, y_pred))

RMSE: 21.836374571441247
R2: 0.7573864996073563

In [135]:
# Ridge Regression
from  sklearn.linear_model import Ridge 
from sklearn.metrics import mean_squared_error, r2_score

ridge = Ridge(alpha = 0.1)
ridge.fit(x_train_poly, y_train)

# Predictions
y_pred = ridge.predict(x_test_poly)

# Model Evaluation
print('RMSE:', mean_squared_error(y_test, y_pred))
print('R2:', r2_score(y_test, y_pred))

RMSE: 11.727444757983223
R2: 0.8697019775839154

In [136]:
# Lasso Regression
from sklearn.linear_model import Lasso

lasso = Lasso(alpha=0.01, max_iter=10000)
lasso.fit(x_train_poly, y_train)

# Predictions
y_pred = lasso.predict(x_test_poly)

# Model Evaluation
print('RMSE:', mean_squared_error(y_test, y_pred))
print('R2:', r2_score(y_test, y_pred))

RMSE: 11.811780786015476
R2: 0.8687649603650921

In [ ]:
# Lasso Regression
from sklearn.linear_model import Lasso

lasso = Lasso(alpha=0.01) # Objective did not converge
lasso.fit(x_train_poly, y_train)

# Predictions
y_pred = lasso.predict(x_test_poly)

# Model Evaluation
print('RMSE:', mean_squared_error(y_test, y_pred))
print('R2:', r2_score(y_test, y_pred))

RMSE: 11.811780786015476
R2: 0.8687649603650921

In [ ]:
for alpha in [0, 0.01, 0.1, 1, 10, 100]: # alpha = 0 means polynomial without regularization
    ridge = Ridge(alpha=alpha)
    ridge.fit(x_train_poly, y_train)
    y_pred = ridge.predict(x_test_poly)
    print('alpha:', alpha)
    print('RMSE:', mean_squared_error(y_test, y_pred))
    print('R2:', r2_score(y_test, y_pred))
    print('--------------------------------------')

alpha: 0
RMSE: 11.70030834074733
R2: 0.8700034773201548
--------------------------------------
alpha: 0.01
RMSE: 11.725024152969736
R2: 0.8697288717669891
--------------------------------------
alpha: 0.1
RMSE: 11.727444757983223
R2: 0.8697019775839154
--------------------------------------
alpha: 1
RMSE: 11.745829974310352
R2: 0.8694977082500108
--------------------------------------
alpha: 10
RMSE: 11.770787298816515
R2: 0.8692204193695208
--------------------------------------
alpha: 100
RMSE: 12.289413672262043
R2: 0.8634582101050706
--------------------------------------

In [ ]:
# Plynomial Regresssion 
from sklearn.preprocessing import PolynomialFeatures


# Preprocessing for numerical data
numerical_transformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                                        ('poly', PolynomialFeatures(degree=2)), 
                                        ('scaler', StandardScaler())])

# Preprocessing for categorical data
nominal_categorical_transformer = Pipeline(steps=[('binary', BinaryEncoder())])
ordinal_categorical_transformer = Pipeline(steps=[('ordinal', OrdinalEncoder(categories=[['Fourth & Above', 'Third', 'Second', 'First']]))])

# Bundle preprocessing for numerical and categorical data
preprocessor = ColumnTransformer(transformers=[('num_prep', numerical_transformer, num_cols),
                                               ('nom_prep', nominal_categorical_transformer, nom_cat_cols),
                                               ('ord_prep', ordinal_categorical_transformer, ord_cat_cols)])

x_train_poly = preprocessor.fit_transform(x_train)
x_test_poly = preprocessor.transform(x_test)

In [139]:
def prep(poly_degree):
    # Preprocessing for numerical data
    numerical_transformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                                        ('poly', PolynomialFeatures(degree=poly_degree)), 
                                        ('scaler', StandardScaler())])

# Preprocessing for categorical data
    nominal_categorical_transformer = Pipeline(steps=[('binary', BinaryEncoder())])
    ordinal_categorical_transformer = Pipeline(steps=[('ordinal', OrdinalEncoder(categories=[['Fourth & Above', 'Third', 'Second', 'First']]))])

# Bundle preprocessing for numerical and categorical dat
    prep = ColumnTransformer(transformers=[('num_prep', numerical_transformer, num_cols),
                                               ('nom_prep', nominal_categorical_transformer, nom_cat_cols),
                                               ('ord_prep', ordinal_categorical_transformer, ord_cat_cols)])
    
    return prep

In [ ]:
for degree in [2, 3, 4, 5]:
    ridge = Ridge(alpha= 0.1)
    preprocessor = prep(degree)
    x_train_poly = preprocessor.fit_transform(x_train)
    x_test_poly = preprocessor.transform(x_test)
    ridge.fit(x_train_poly, y_train)
    y_pred = ridge.predict(x_test_poly)
    print('degree:', degree)
    print('RMSE:', mean_squared_error(y_test, y_pred))
    print('R2:', r2_score(y_test, y_pred))
    print('-----------------------------------------')

degree: 2
RMSE: 11.727444757983223
R2: 0.8697019775839154
-----------------------------------------
degree: 3
RMSE: 11.374688925982625
R2: 0.8736212786980077
-----------------------------------------
degree: 4
RMSE: 11.105645273633716
R2: 0.876610493873871
-----------------------------------------
degree: 5
RMSE: 11.065443515052952
R2: 0.877057156360783
-----------------------------------------

In [143]:
for degree in [2, 3, 4, 5]:
    for alpha in [0.01, 0.1, 1, 10]:
     ridge = Ridge(alpha= 0.1)
     preprocessor = prep(degree)
     x_train_poly = preprocessor.fit_transform(x_train)
     x_test_poly = preprocessor.transform(x_test)
     ridge.fit(x_train_poly, y_train)
     y_pred = ridge.predict(x_test_poly)
     print('degree:', degree)
     print('RMSE:', mean_squared_error(y_test, y_pred))
     print('R2:', r2_score(y_test, y_pred))
     print('-----------------------------------------')

degree: 2
RMSE: 11.727444757983223
R2: 0.8697019775839154
-----------------------------------------
degree: 2
RMSE: 11.727444757983223
R2: 0.8697019775839154
-----------------------------------------
degree: 2
RMSE: 11.727444757983223
R2: 0.8697019775839154
-----------------------------------------
degree: 2
RMSE: 11.727444757983223
R2: 0.8697019775839154
-----------------------------------------
degree: 3
RMSE: 11.374688925982625
R2: 0.8736212786980077
-----------------------------------------
degree: 3
RMSE: 11.374688925982625
R2: 0.8736212786980077
-----------------------------------------
degree: 3
RMSE: 11.374688925982625
R2: 0.8736212786980077
-----------------------------------------
degree: 3
RMSE: 11.374688925982625
R2: 0.8736212786980077
-----------------------------------------
degree: 4
RMSE: 11.105645273633716
R2: 0.876610493873871
-----------------------------------------
degree: 4
RMSE: 11.105645273633716
R2: 0.876610493873871
-----------------------------------------
degree: 4
RMSE: 11.105645273633716
R2: 0.876610493873871
-----------------------------------------
degree: 4
RMSE: 11.105645273633716
R2: 0.876610493873871
-----------------------------------------
degree: 5
RMSE: 11.065443515052952
R2: 0.877057156360783
-----------------------------------------
degree: 5
RMSE: 11.065443515052952
R2: 0.877057156360783
-----------------------------------------
degree: 5
RMSE: 11.065443515052952
R2: 0.877057156360783
-----------------------------------------
degree: 5
RMSE: 11.065443515052952
R2: 0.877057156360783
-----------------------------------------

In [144]:
# Final Model

model = Pipeline(steps=[('preprocessor', prep(2)),
                        ('model', LinearRegression())])

model.fit(x_train, y_train)

# Predictions
y_pred = model.predict(x_test)

# Model Evaluation
print('R2:', model.score(x_test, y_test))

R2: 0.8697319236991381

In [147]:
def prep_and_fit(poly_degreex, alpha):
    ridge = Ridge(alpha=alpha)
    model = Pipeline(steps=[('preprocessor', prep(poly_degreex)),
                            ('model', Ridge(alpha=alpha))])
    model.fit(x_train, y_train)
    test_score = r2_score(y_test, model.predict(x_test))
    return test_score

In [148]:
prep_and_fit(3, 0.1)

0.8736212786980077

- x_test,train -- y_test,train understanding

⚡ Analogy (classroom):

Training phase: Teacher gives practice problems (x_train) and the answers (y_train). Student learns.

Testing phase: Teacher gives a new problem (x_test). The student solves it. Teacher then compares the student’s answer with the true answer (y_test).

# Cross Validation

In [151]:
from sklearn.model_selection import cross_val_score

model = Pipeline(steps=[('preprocessor', prep(2)),
                        ('model', LinearRegression())])

scores = cross_val_score(model, x_train, y_train, cv=3,
scoring='r2')
scores

array([0.85440124, 0.87280026, 0.83458068])

In [152]:
print('Mean CV R2:', scores.mean())
print('Std Dev of CV R2:', scores.std())

Mean CV R2: 0.8539273943858711
Std Dev of CV R2: 0.015606678002732428

# Hyperparameter Tuning

In [163]:
from sklearn.model_selection import GridSearchCV

numerical_transformer = Pipeline(steps=[ ('imputer', SimpleImputer(strategy='median')),
                                        ('poly', PolynomialFeatures()),
                                        ('scalar', StandardScaler())])

# Preprocessing for categorical data
nominal_categorical_transformer = Pipeline(steps=[('binary', BinaryEncoder())])
ordinal_categorical_transformer = Pipeline(steps=[('ordinal', OrdinalEncoder(categories=[['Fourth & Above', 'Third', 'Second', 'First']]))])

# Bundle preprocessing for numerical and categorical data
preprocessor = ColumnTransformer(transformers=[('num_prep', numerical_transformer, num_cols),
                                               ('nom_prep', nominal_categorical_transformer, nom_cat_cols),
                                               ('ord_prep', ordinal_categorical_transformer, ord_cat_cols)])

model = Pipeline(steps=[('preprocessor', preprocessor),
                        ('model', Ridge())])

param_grid = {
    'preprocessor__num_prep__poly__degree': [2, 3, 4],
    'model__alpha': [0.01, 0.1, 1, 10]
             }

grid_search = GridSearchCV(model, param_grid, cv=5, scoring='r2', n_jobs=-1, verbose=1)  # using all possible cores i have
  # verbose : bydeni info during training
grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

KeyboardInterrupt:

- 12 candidates : means combination between each polynomial degree and each alpha

In [ ]:
grid_search.best_params_

{'model__alpha': 0.01, 'preprocessor__num_prep__poly__degree': 4}

In [ ]:
pd.DataFrame(grid_search.cv_results_)

    mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0           0.240         0.038  ...           0.029               10
1           0.298         0.059  ...           0.029                4
2           0.407         0.031  ...           0.030                1
3           0.295         0.016  ...           0.029                9
4           0.316         0.034  ...           0.029                5
5           0.358         0.016  ...           0.030                2
6           0.276         0.019  ...           0.029               11
7           0.295         0.014  ...           0.028                6
8           0.337         0.018  ...           0.029                3
9           0.264         0.014  ...           0.030               12
10          0.303         0.012  ...           0.028                8
11          0.286         0.025  ...           0.028                7

[12 rows x 15 columns]

In [ ]:
pd.DataFrame(grid_search.cv_results_)[['param_model__alpha', 'param_preprocessor__num_prep__poly__degree', 'mean_test_score', 'rank_test_score']]

    param_model__alpha  ...  rank_test_score
0                0.010  ...               10
1                0.010  ...                4
2                0.010  ...                1
3                0.100  ...                9
4                0.100  ...                5
5                0.100  ...                2
6                1.000  ...               11
7                1.000  ...                6
8                1.000  ...                3
9               10.000  ...               12
10              10.000  ...                8
11              10.000  ...                7

[12 rows x 4 columns]

In [ ]:
grid_search.best_estimator_

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num_prep',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('poly',
                                                                   PolynomialFeatures(degree=4)),
                                                                  ('scalar',
                                                                   StandardScaler())]),
                                                  ['Kilometers_Driven',
                                                   'Mileage', 'Engine', 'Power',
                                                   'Age']),
                                                 ('nom_prep',
                                                  Pipeline(steps=[('binary',
                                                                   BinaryEncoder())]),
                                                  ['Location', 'Fuel_Type',
                                                   'Transmission', 'Brand',
                                                   'Model']),
                                                 ('ord_prep',
                                                  Pipeline(steps=[('ordinal',
                                                                   OrdinalEncoder(categories=[['Fourth '
                                                                                               '& '
                                                                                               'Above',
                                                                                               'Third',
                                                                                               'Second',
                                                                                               'First']]))]),
                                                  ['Owner_Type'])])),
                ('model', Ridge(alpha=0.01))])

In [ ]:
model= grid_search.best_estimator_
model.fit(x_train, y_train) # Not needed as already fitted

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num_prep',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('poly',
                                                                   PolynomialFeatures(degree=4)),
                                                                  ('scalar',
                                                                   StandardScaler())]),
                                                  ['Kilometers_Driven',
                                                   'Mileage', 'Engine', 'Power',
                                                   'Age']),
                                                 ('nom_prep',
                                                  Pipeline(steps=[('binary',
                                                                   BinaryEncoder())]),
                                                  ['Location', 'Fuel_Type',
                                                   'Transmission', 'Brand',
                                                   'Model']),
                                                 ('ord_prep',
                                                  Pipeline(steps=[('ordinal',
                                                                   OrdinalEncoder(categories=[['Fourth '
                                                                                               '& '
                                                                                               'Above',
                                                                                               'Third',
                                                                                               'Second',
                                                                                               'First']]))]),
                                                  ['Owner_Type'])])),
                ('model', Ridge(alpha=0.01))])

- GridSearchCV
 - Ridge + Polynomial Features : Hyperparameter Tuning with CV >> Best Estimator(1)
 - Decision Tree Regressor : Hyperparameter Tuning with CV >> Best Estimator(2)
 - Random Forest Regressor:Hyperparameter Tuning with CV >> Best Estimator(3)

All the above models are trained on Training Set with Cross Validation and Hyperparameter Tuning
- Choose the Best Model >> Final Evaluation on Test Set

In [ ]:
print('Test R2:', model.score(x_test, y_test))

Test R2: 0.8777462412690902

Suppose X_train = first 4 houses.

Suppose X_test = last 2 houses.

📌 The model learns from the training houses how size, rooms, and location affect the price.

📌 Then we give it the X_test houses (their size, rooms, location), and ask:
👉 “Can you guess their price?”

Finally, we compare the predicted price vs the actual y_test (real price).

✅ So, X_test is just the real-life unseen houses (or data points) we keep aside to check if our model can make good predictions on data it never saw before.

In [164]:
# Log Transform for the target
def log_transform(x):
    return np.log1p(x)

# Log Transform
y_train_log = log_transform(y_train)
y_test_log = log_transform(y_test)

In [169]:
x = 100
np.log(x + 1)

np.float64(4.61512051684126)

In [170]:
y_train

3130    4.750
1753   38.000
5619    9.270
709     8.500
2411   10.450
        ...
3996    2.000
5504    3.250
5540   15.000
5712    2.300
926     6.500
Name: Price, Length: 4495, dtype: float64

In [178]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig  = make_subplots(rows=1, cols=2, subplot_titles=['Before Log Transform', 'After Log Transform'])

fig.add_trace(go.Histogram(x=y_train, name='Before Log Transform'), row=1, col=1)
fig.add_trace(go.Histogram(x=y_train_log, name='After Log Transform'), row=1, col=2)


fig.show()

In [179]:
grid_search = GridSearchCV(model, param_grid, cv=5, scoring='r2', n_jobs=-1, verbose=1)
grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num_prep',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('poly',
                                                                                          PolynomialFeatures()),
                                                                                         ('scalar',
                                                                                          StandardScaler())]),
                                                                         ['Kilometers_Driven',
                                                                          'Mileage',
                                                                          'Engine',
                                                                          'Power',
                                                                          'Age']),
                                                                        ('nom_prep',
                                                                         Pipeline(steps=[('binary',
                                                                                          BinaryEncoder())]),
                                                                         ['Location',
                                                                          'Fuel_Type',
                                                                          'Transmission',
                                                                          'Brand',
                                                                          'Model']),
                                                                        ('ord_prep',
                                                                         Pipeline(steps=[('ordinal',
                                                                                          OrdinalEncoder(categories=[['Fourth '
                                                                                                                      '& '
                                                                                                                      'Above',
                                                                                                                      'Third',
                                                                                                                      'Second',
                                                                                                                      'First']]))]),
                                                                         ['Owner_Type'])])),
                                       ('model', Ridge())]),
             n_jobs=-1,
             param_grid={'model__alpha': [0.01, 0.1, 1, 10],
                         'preprocessor__num_prep__poly__degree': [2, 3, 4]},
             scoring='r2', verbose=1)

In [180]:
grid_search.best_params_

{'model__alpha': 0.01, 'preprocessor__num_prep__poly__degree': 4}

In [182]:
grid_search.best_score_

np.float64(0.8735068544368536)

In [181]:
best_model = grid_search.best_estimator_
best_model.fit(x_train, y_train_log)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num_prep',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('poly',
                                                                   PolynomialFeatures(degree=4)),
                                                                  ('scalar',
                                                                   StandardScaler())]),
                                                  ['Kilometers_Driven',
                                                   'Mileage', 'Engine', 'Power',
                                                   'Age']),
                                                 ('nom_prep',
                                                  Pipeline(steps=[('binary',
                                                                   BinaryEncoder())]),
                                                  ['Location', 'Fuel_Type',
                                                   'Transmission', 'Brand',
                                                   'Model']),
                                                 ('ord_prep',
                                                  Pipeline(steps=[('ordinal',
                                                                   OrdinalEncoder(categories=[['Fourth '
                                                                                               '& '
                                                                                               'Above',
                                                                                               'Third',
                                                                                               'Second',
                                                                                               'First']]))]),
                                                  ['Owner_Type'])])),
                ('model', Ridge(alpha=0.01))])

**Log Transformation of the target variable affects the model performance positively

In [183]:
best_model.predict(x_test.iloc[0].to_frame().T)  # this is log(price + 1) not price

array([1.9252686])

In [184]:
log_price = best_model.predict(x_test.iloc[0].to_frame().T)
np.expm1(log_price)  # Convert back to price

array([5.8569902])

In [185]:
y_test.iloc[0] # actual price

np.float64(5.1)

# Saving

In [186]:
import pickle  # or import joblib

# Model saving
pickle.dump(best_model, open('ml_model.pkl', 'wb'))

In [187]:
# Inferencing

loaded_model = pickle.load(open('ml_model.pkl', 'rb'))

In [188]:
# New Data 
new_data = x_test.sample(1)
new_data

     Location  Kilometers_Driven Fuel_Type  ... Brand   Model  Age
2687    Kochi              20469    Petrol  ...  Mini  Cooper    3

[1 rows x 12 columns]

In [189]:
y_test[new_data.index]

2687   35.980
Name: Price, dtype: float64

In [190]:
# Preprocessing & Prediction
log_price = loaded_model.predict(new_data)  # in log scale
price = np.expm1(log_price)  # in original scale

print('Price:', price[0])

Price: 34.62505183411786